CPU: Testbench.v CPU.v PC.v Registers.v Instruction_Memory.v Adder.v ALU.v MUX32.v Sign_Extend.v Control.v ALU_Control.v
	iverilog -o CPU Testbench.v CPU.v PC.v Registers.v Instruction_Memory.v Adder.v ALU.v MUX32.v Sign_Extend.v Control.v ALU_Control.v
